export const seoKeywords = [
  "Saif Ali",
  "Web Developer",
  "Web Designer",
  "Portfolio",
  "DevMode",
  "UI designer",
  "Frontend developer",
  "Backend developer",
  "Fullstack developer",
  "React developer",
  "Next.js developer",
  "Node.js developer",
  "Express.js developer",
  "MongoDB developer",
  "MERN stack developer",
  "Software developer",
  "Software engineer",
  "Web developer in Pakistan",
  "Web developer in Rawalpindi",
];
